config/routes.rb
Rails.application.routes.draw do
  resources :chapters do
    resources :lessons
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :lessons
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates :title, :presence => true
  validates :number, :presence => true
  validates :content, :presence => true
  belongs_to :chapter

  default_scope { order('number ASC')}

  def next
    if self.number
      Lesson.where(:number => (self.number + 1),:chapter_id => self.chapter_id).first
    end
  end

  def previous
    if self.number
      Lesson.where(:number => (self.number - 1),:chapter_id => self.chapter_id).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  #----------------- CREATE ----------------- #
  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to chapters_path
    else
      render :new
    end
  end


  #----------------- UPDATE ----------------- #

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    if @chapter.update(chapter_params)
      redirect_to chapters_path
    else
      render :edit
    end
  end

  #----------------- DESTROY ----------------- #

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy
    redirect_to chapters_path
  end


private
def chapter_params
  params.require(:chapter).permit(:name)
end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

def show
  @chapter = Chapter.find(params[:chapter_id])
  @lesson = Lesson.find(params[:id])
end

#----------------- CREATE ----------------- #

def new
  @chapter = Chapter.find(params[:chapter_id])
  @lesson = @chapter.lessons.new
end

def create
  @chapter = Chapter.find(params[:chapter_id])
  @lesson = @chapter.lessons.new(lesson_params)
  if @lesson.save
    redirect_to chapters_path(@lesson.chapter)
  else
    render :new
  end
end

#----------------- UPDATE ----------------- #

def edit
  @chapter = Chapter.find(params[:chapter_id])
  @lesson = @chapter.lessons.find(params[:id])
end

def update
  @chapter = Chapter.find(params[:chapter_id])
  @lesson = @chapter.lessons.find(params[:id])
  if @lesson.update(lesson_params)
    redirect_to chapter_lesson_path(@chapter, @lesson)
  else
    render :edit
  end
end

#----------------- DESTROY ----------------- #

def destroy
  @chapter = Chapter.find(params[:chapter_id])
  @lesson = @chapter.lessons.find(params[:id])
  @lesson.destroy
  redirect_to chapter_path(@chapter)
end

#-------------------------------------------- #

private
def lesson_params
  params.require(:lesson).permit(:title, :content, :number)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= form_for @chapter do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/chapters/edit.html.erb
<h2>Edit Chapter</h2>
<%= render "form" %>

app/views/chapters/index.html.erb
<h1>Table of Contents</h1>

<button class="btn btn-danger"><%= link_to "Add New Chapter", new_chapter_path %></button>

<br>

<% @chapters.all.each do |chapter| %>
  <div class="chapter-box col-md-6">
    <h3><%= link_to chapter.name, chapter_path(chapter) %></h3>
    <span>
      | <%= link_to "Edit", edit_chapter_path(chapter) %> |
      <%= link_to "Delete", chapter_path(chapter), :data => {:confirm => "Are you sure?", :method => "delete"} %>
    </span>

    <ul>
      <% chapter.lessons.all.each do |lesson| %>
        <li><%= link_to lesson.title, chapter_lesson_path(chapter, lesson) %></li>
      <% end %>
    </ul>

  </div>
<% end %>


<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/chapters">Table of Contents</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/chapters/new.html.erb
<h4>Add chapter</h4>

<%= render 'form' %>

app/views/chapters/show.html.erb
<h1><%= @chapter.name %></h1>

<button class="btn btn-danger"><%= link_to "Add Lesson", new_chapter_lesson_path(@chapter) %></button>

<br>
<br>

<ul>
  <% @chapter.lessons.each do |lesson| %>
    <li><%= link_to lesson.title, chapter_lesson_path(@chapter, lesson) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnHowToProgram</title>

  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>


  <div class="container">
    <%= yield %>
  </div>

<!-- Fixed navbar -->

<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
      <div id="navbar" class="collapse navbar-collapse">

        <ul class="nav navbar-nav">
          <%= yield(:navleft) %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= yield(:navbar) %>
          <li><a href="/chapters">Table of Contents</a></li>
        </ul>
      </div>
  </div>
</nav>

</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for [@chapter, @lesson] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>

  <%= f.label :number %>
  <%= f.number_field :number %> <br>

  <%= f.label :content %> <br>
  <%= f.text_area :content %> <br>

  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<%= render 'form' %>

app/views/lessons/new.html.erb
<h1>Add lesson</h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<h1><%= @lesson.title %></h1>
<button class="btn btn-danger"><%= link_to 'Edit', edit_chapter_lesson_path(@chapter, @lesson) %></button>
<button class="btn btn-danger"><%= link_to "Delete", chapter_lesson_path(@chapter, @lesson), :data => {:confirm => "Are you sure?", :method => "delete"}  %></button>

<br>
<br>

<p><%= @lesson.content %></p>

<%= content_for(:navleft) do %>
  <li>
    <% if @lesson.previous %>
      <a href="/chapters/<%= @chapter.id %>/lessons/<%= @lesson.previous.id%>">Previous Lesson</a><br>
    <% end %>
  </li>

  <li>
    <% if @lesson.next %>
      <a href="/chapters/<%= @chapter.id %>/lessons/<%= @lesson.next.id%>">Next Lesson</a><br>
    <% end %>
  </li>
<% end %>


<%= content_for(:navbar) do %>
  <li><a href="/chapters">Section Contents</a></li>
<% end %>